# tag_push自动部署准备阶段
prepare: &prepare
  script: |
    CNB_BRANCH_ENV=${CNB_BRANCH%%-*}
    CNB_VERSION=${CNB_BRANCH#*-}
    IMAGE_TAG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${CNB_BRANCH_ENV}:${CNB_VERSION}
    printf "##[set-output cnb_branch_env=%s]\n" "$CNB_BRANCH_ENV"
    printf "##[set-output cnb_version=%s]\n" "$CNB_VERSION"
    printf "##[set-output image_tag=%s]\n" "$IMAGE_TAG"

  exports:
    cnb_branch_env: CNB_BRANCH_ENV
    cnb_version: CNB_VERSION
    image_tag: IMAGE_TAG

# web按钮手动触发部署前置准备
web_trigger_prepare: &web_prepare
  script: |
    CNB_BRANCH_ENV=${tag_name%%-*}
    CNB_VERSION=${tag_name#*-}
    IMAGE_TAG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${CNB_BRANCH_ENV}:${CNB_VERSION}
    printf "##[set-output image_tag=%s]\n" "$IMAGE_TAG"
    printf "##[set-output cnb_branch_env=%s]\n" "$CNB_BRANCH_ENV"
  exports:
    cnb_branch_env: CNB_BRANCH_ENV
    image_tag: IMAGE_TAG


# Docker build && Docker push
build_push: &build_push
  script: |
    echo "build_push image_tag: $IMAGE_TAG, env: $CNB_BRANCH_ENV, version: $CNB_VERSION"
    docker build -t $IMAGE_TAG . --build-arg BUILD_ENV=$CNB_BRANCH_ENV
    docker push $IMAGE_TAG

# ----------------------
# Pipeline 定义模板
# ----------------------
pipeline: &pipeline
  name: cnb-pipeline
  services:
    - docker
  stages:
    - name: prepare
      <<: *prepare
    - name: build push
      jobs:
        <<: *build_push
    - name: tke deploy
      if: |
        [ "${CNB_BRANCH_ENV}" == "dev" ]
      image: tencentcom/deploy-to-tke
      settingsFrom: https://cnb.cool/byboat/edu.boat.secret/-/blob/main/tke_secret.yml
      settings:
        region: ap-shanghai
        cluster_id: cls-el54b7pt
        namespace: ${CNB_BRANCH_ENV}
        workload_kind: deployment
        workload_name: byboat-admin-dev-deploy
        container_names: byboat-admin-dev
        container_images: $IMAGE_TAG
  failStages:
    - name: notify-feishu-card
      script: |
        curl -X "POST" "https://open.feishu.cn/open-apis/bot/v2/hook/6eccbc0d-6b44-45de-916b-25f2ed24d39c" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "interactive",
            "card": {
              "header": {
                "title": {
                  "tag": "plain_text",
                  "content": "❌ 构建失败"
                },
                "template": "red"
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**仓库：** '$CNB_REPO_SLUG'\n**分支：** '$CNB_BRANCH'\n**触发人：** '$CNB_BUILD_USER'\n"
                  }
                },
                {
                  "tag": "action",
                  "actions": [
                    {
                      "tag": "button",
                      "text": {
                        "tag": "plain_text",
                        "content": "查看详情"
                      },
                      "url": "'$CNB_BUILD_WEB_URL'",
                      "type": "primary"
                    }
                  ]
                }
              ]
            }
          }'


$:
  tag_push:
    - <<: *pipeline


"**":
  # 开发环境手动部署
  web_trigger_dev:
    - stages:
        - name: 手动部署前置准备
          <<: *web_prepare

        - name: 开发环境手动部署
          image: tencentcom/deploy-to-tke
          settingsFrom: https://cnb.cool/byboat/edu.boat.secret/-/blob/main/tke_secret.yml
          settings:
            region: ap-shanghai
            cluster_id: cls-el54b7pt
            namespace: dev
            workload_kind: deployment
            workload_name: byboat-admin-dev-deploy
            container_names: byboat-admin-dev
            container_images: $IMAGE_TAG

  # 生产环境手动部署
  web_trigger_prod:
    - stages:
        - name: 手动部署前置准备
          <<: *web_prepare

        - name: 生产环境手动部署
          image: tencentcom/deploy-to-tke
          settingsFrom: https://cnb.cool/byboat/edu.boat.secret/-/blob/main/tke_secret.yml
          settings:
            region: ap-shanghai
            cluster_id: cls-el54b7pt
            namespace: prod
            workload_kind: deployment
            workload_name: prod-byboat-admin-deploy
            container_names: prod-byboat-admin
            container_images: $IMAGE_TAG
