FROM openresty/openresty:centos

USER root
RUN rm -rf /etc/yum.repos.d/CentOS-Linux-*.repo
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-8.repo
RUN yum clean all && yum makecache
# 安装 Node.js
RUN curl -sL https://rpm.nodesource.com/setup_current.x | bash -
RUN yum install -y nodejs
RUN npm config set registry https://registry.npmmirror.com
# 安装pnpm
RUN npm install -g pnpm
# 安装yarn
RUN npm install -g yarn
# 清理缓存
RUN yum clean all

## 该镜像完成后续对 /etc/nginx/conf.d/defualt.conf中,在loccation / {xxx} 中增加： try_files $uri $uri/ /index.html; location /web-cdn/ { root   /usr/local/openresty/nginx/html; } 指令后重新打包镜像
