// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newCourseCatalog(db *gorm.DB, opts ...gen.DOOption) courseCatalog {
	_courseCatalog := courseCatalog{}

	_courseCatalog.courseCatalogDo.UseDB(db, opts...)
	_courseCatalog.courseCatalogDo.UseModel(&model.CourseCatalog{})

	tableName := _courseCatalog.courseCatalogDo.TableName()
	_courseCatalog.ALL = field.NewAsterisk(tableName)
	_courseCatalog.ID = field.NewInt64(tableName, "id")
	_courseCatalog.ParentID = field.NewInt64(tableName, "parent_id")
	_courseCatalog.Level = field.NewInt32(tableName, "level")
	_courseCatalog.Name = field.NewString(tableName, "name")
	_courseCatalog.GoodsID = field.NewInt64(tableName, "goods_id")
	_courseCatalog.Sort = field.NewInt64(tableName, "sort")
	_courseCatalog.UpdateAt = field.NewTime(tableName, "update_at")
	_courseCatalog.UpdateBy = field.NewInt64(tableName, "update_by")

	_courseCatalog.fillFieldMap()

	return _courseCatalog
}

// courseCatalog 课程目录表
type courseCatalog struct {
	courseCatalogDo courseCatalogDo

	ALL      field.Asterisk
	ID       field.Int64
	ParentID field.Int64
	Level    field.Int32
	Name     field.String
	GoodsID  field.Int64
	Sort     field.Int64
	UpdateAt field.Time
	UpdateBy field.Int64

	fieldMap map[string]field.Expr
}

func (c courseCatalog) Table(newTableName string) *courseCatalog {
	c.courseCatalogDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c courseCatalog) As(alias string) *courseCatalog {
	c.courseCatalogDo.DO = *(c.courseCatalogDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *courseCatalog) updateTableName(table string) *courseCatalog {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.Level = field.NewInt32(table, "level")
	c.Name = field.NewString(table, "name")
	c.GoodsID = field.NewInt64(table, "goods_id")
	c.Sort = field.NewInt64(table, "sort")
	c.UpdateAt = field.NewTime(table, "update_at")
	c.UpdateBy = field.NewInt64(table, "update_by")

	c.fillFieldMap()

	return c
}

func (c *courseCatalog) WithContext(ctx context.Context) *courseCatalogDo {
	return c.courseCatalogDo.WithContext(ctx)
}

func (c courseCatalog) TableName() string { return c.courseCatalogDo.TableName() }

func (c courseCatalog) Alias() string { return c.courseCatalogDo.Alias() }

func (c courseCatalog) Columns(cols ...field.Expr) gen.Columns {
	return c.courseCatalogDo.Columns(cols...)
}

func (c *courseCatalog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *courseCatalog) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["level"] = c.Level
	c.fieldMap["name"] = c.Name
	c.fieldMap["goods_id"] = c.GoodsID
	c.fieldMap["sort"] = c.Sort
	c.fieldMap["update_at"] = c.UpdateAt
	c.fieldMap["update_by"] = c.UpdateBy
}

func (c courseCatalog) clone(db *gorm.DB) courseCatalog {
	c.courseCatalogDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c courseCatalog) replaceDB(db *gorm.DB) courseCatalog {
	c.courseCatalogDo.ReplaceDB(db)
	return c
}

type courseCatalogDo struct{ gen.DO }

func (c courseCatalogDo) Debug() *courseCatalogDo {
	return c.withDO(c.DO.Debug())
}

func (c courseCatalogDo) WithContext(ctx context.Context) *courseCatalogDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c courseCatalogDo) ReadDB() *courseCatalogDo {
	return c.Clauses(dbresolver.Read)
}

func (c courseCatalogDo) WriteDB() *courseCatalogDo {
	return c.Clauses(dbresolver.Write)
}

func (c courseCatalogDo) Session(config *gorm.Session) *courseCatalogDo {
	return c.withDO(c.DO.Session(config))
}

func (c courseCatalogDo) Clauses(conds ...clause.Expression) *courseCatalogDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c courseCatalogDo) Returning(value interface{}, columns ...string) *courseCatalogDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c courseCatalogDo) Not(conds ...gen.Condition) *courseCatalogDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c courseCatalogDo) Or(conds ...gen.Condition) *courseCatalogDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c courseCatalogDo) Select(conds ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c courseCatalogDo) Where(conds ...gen.Condition) *courseCatalogDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c courseCatalogDo) Order(conds ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c courseCatalogDo) Distinct(cols ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c courseCatalogDo) Omit(cols ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c courseCatalogDo) Join(table schema.Tabler, on ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c courseCatalogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c courseCatalogDo) RightJoin(table schema.Tabler, on ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c courseCatalogDo) Group(cols ...field.Expr) *courseCatalogDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c courseCatalogDo) Having(conds ...gen.Condition) *courseCatalogDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c courseCatalogDo) Limit(limit int) *courseCatalogDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c courseCatalogDo) Offset(offset int) *courseCatalogDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c courseCatalogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *courseCatalogDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c courseCatalogDo) Unscoped() *courseCatalogDo {
	return c.withDO(c.DO.Unscoped())
}

func (c courseCatalogDo) Create(values ...*model.CourseCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c courseCatalogDo) CreateInBatches(values []*model.CourseCatalog, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c courseCatalogDo) Save(values ...*model.CourseCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c courseCatalogDo) First() (*model.CourseCatalog, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseCatalog), nil
	}
}

func (c courseCatalogDo) Take() (*model.CourseCatalog, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseCatalog), nil
	}
}

func (c courseCatalogDo) Last() (*model.CourseCatalog, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseCatalog), nil
	}
}

func (c courseCatalogDo) Find() ([]*model.CourseCatalog, error) {
	result, err := c.DO.Find()
	return result.([]*model.CourseCatalog), err
}

func (c courseCatalogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CourseCatalog, err error) {
	buf := make([]*model.CourseCatalog, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c courseCatalogDo) FindInBatches(result *[]*model.CourseCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c courseCatalogDo) Attrs(attrs ...field.AssignExpr) *courseCatalogDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c courseCatalogDo) Assign(attrs ...field.AssignExpr) *courseCatalogDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c courseCatalogDo) Joins(fields ...field.RelationField) *courseCatalogDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c courseCatalogDo) Preload(fields ...field.RelationField) *courseCatalogDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c courseCatalogDo) FirstOrInit() (*model.CourseCatalog, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseCatalog), nil
	}
}

func (c courseCatalogDo) FirstOrCreate() (*model.CourseCatalog, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseCatalog), nil
	}
}

func (c courseCatalogDo) FindByPage(offset int, limit int) (result []*model.CourseCatalog, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c courseCatalogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c courseCatalogDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c courseCatalogDo) Delete(models ...*model.CourseCatalog) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *courseCatalogDo) withDO(do gen.Dao) *courseCatalogDo {
	c.DO = *do.(*gen.DO)
	return c
}
