// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		AdminUser:          newAdminUser(db, opts...),
		AdminUserRole:      newAdminUserRole(db, opts...),
		AppUser:            newAppUser(db, opts...),
		CourseCatalog:      newCourseCatalog(db, opts...),
		CourseGood:         newCourseGood(db, opts...),
		CourseLesson:       newCourseLesson(db, opts...),
		MobileUser:         newMobileUser(db, opts...),
		Order:              newOrder(db, opts...),
		OrderItem:          newOrderItem(db, opts...),
		Permission:         newPermission(db, opts...),
		ResourceUploadFile: newResourceUploadFile(db, opts...),
		Role:               newRole(db, opts...),
		RolePermission:     newRolePermission(db, opts...),
		SmsTemplate:        newSmsTemplate(db, opts...),
		User:               newUser(db, opts...),
		UserCourseGood:     newUserCourseGood(db, opts...),
		WechatUser:         newWechatUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AdminUser          adminUser
	AdminUserRole      adminUserRole
	AppUser            appUser
	CourseCatalog      courseCatalog
	CourseGood         courseGood
	CourseLesson       courseLesson
	MobileUser         mobileUser
	Order              order
	OrderItem          orderItem
	Permission         permission
	ResourceUploadFile resourceUploadFile
	Role               role
	RolePermission     rolePermission
	SmsTemplate        smsTemplate
	User               user
	UserCourseGood     userCourseGood
	WechatUser         wechatUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		AdminUser:          q.AdminUser.clone(db),
		AdminUserRole:      q.AdminUserRole.clone(db),
		AppUser:            q.AppUser.clone(db),
		CourseCatalog:      q.CourseCatalog.clone(db),
		CourseGood:         q.CourseGood.clone(db),
		CourseLesson:       q.CourseLesson.clone(db),
		MobileUser:         q.MobileUser.clone(db),
		Order:              q.Order.clone(db),
		OrderItem:          q.OrderItem.clone(db),
		Permission:         q.Permission.clone(db),
		ResourceUploadFile: q.ResourceUploadFile.clone(db),
		Role:               q.Role.clone(db),
		RolePermission:     q.RolePermission.clone(db),
		SmsTemplate:        q.SmsTemplate.clone(db),
		User:               q.User.clone(db),
		UserCourseGood:     q.UserCourseGood.clone(db),
		WechatUser:         q.WechatUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		AdminUser:          q.AdminUser.replaceDB(db),
		AdminUserRole:      q.AdminUserRole.replaceDB(db),
		AppUser:            q.AppUser.replaceDB(db),
		CourseCatalog:      q.CourseCatalog.replaceDB(db),
		CourseGood:         q.CourseGood.replaceDB(db),
		CourseLesson:       q.CourseLesson.replaceDB(db),
		MobileUser:         q.MobileUser.replaceDB(db),
		Order:              q.Order.replaceDB(db),
		OrderItem:          q.OrderItem.replaceDB(db),
		Permission:         q.Permission.replaceDB(db),
		ResourceUploadFile: q.ResourceUploadFile.replaceDB(db),
		Role:               q.Role.replaceDB(db),
		RolePermission:     q.RolePermission.replaceDB(db),
		SmsTemplate:        q.SmsTemplate.replaceDB(db),
		User:               q.User.replaceDB(db),
		UserCourseGood:     q.UserCourseGood.replaceDB(db),
		WechatUser:         q.WechatUser.replaceDB(db),
	}
}

type queryCtx struct {
	AdminUser          *adminUserDo
	AdminUserRole      *adminUserRoleDo
	AppUser            *appUserDo
	CourseCatalog      *courseCatalogDo
	CourseGood         *courseGoodDo
	CourseLesson       *courseLessonDo
	MobileUser         *mobileUserDo
	Order              *orderDo
	OrderItem          *orderItemDo
	Permission         *permissionDo
	ResourceUploadFile *resourceUploadFileDo
	Role               *roleDo
	RolePermission     *rolePermissionDo
	SmsTemplate        *smsTemplateDo
	User               *userDo
	UserCourseGood     *userCourseGoodDo
	WechatUser         *wechatUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AdminUser:          q.AdminUser.WithContext(ctx),
		AdminUserRole:      q.AdminUserRole.WithContext(ctx),
		AppUser:            q.AppUser.WithContext(ctx),
		CourseCatalog:      q.CourseCatalog.WithContext(ctx),
		CourseGood:         q.CourseGood.WithContext(ctx),
		CourseLesson:       q.CourseLesson.WithContext(ctx),
		MobileUser:         q.MobileUser.WithContext(ctx),
		Order:              q.Order.WithContext(ctx),
		OrderItem:          q.OrderItem.WithContext(ctx),
		Permission:         q.Permission.WithContext(ctx),
		ResourceUploadFile: q.ResourceUploadFile.WithContext(ctx),
		Role:               q.Role.WithContext(ctx),
		RolePermission:     q.RolePermission.WithContext(ctx),
		SmsTemplate:        q.SmsTemplate.WithContext(ctx),
		User:               q.User.WithContext(ctx),
		UserCourseGood:     q.UserCourseGood.WithContext(ctx),
		WechatUser:         q.WechatUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
