// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newOrder(db *gorm.DB, opts ...gen.DOOption) order {
	_order := order{}

	_order.orderDo.UseDB(db, opts...)
	_order.orderDo.UseModel(&model.Order{})

	tableName := _order.orderDo.TableName()
	_order.ALL = field.NewAsterisk(tableName)
	_order.ID = field.NewInt64(tableName, "id")
	_order.OrderNo = field.NewString(tableName, "order_no")
	_order.UserID = field.NewInt64(tableName, "user_id")
	_order.Status = field.NewInt32(tableName, "status")
	_order.OrderSource = field.NewInt32(tableName, "order_source")
	_order.OrderAmount = field.NewInt64(tableName, "order_amount")
	_order.OrderOriginAmount = field.NewInt64(tableName, "order_origin_amount")
	_order.PaymentAmount = field.NewInt64(tableName, "payment_amount")
	_order.TradeNo = field.NewString(tableName, "trade_no")
	_order.InnerTradeNo = field.NewString(tableName, "inner_trade_no")
	_order.OrderDesc = field.NewString(tableName, "order_desc")
	_order.PaymentAt = field.NewInt64(tableName, "payment_at")
	_order.UserRemark = field.NewString(tableName, "user_remark")
	_order.ReceiverConfirmAt = field.NewInt64(tableName, "receiver_confirm_at")
	_order.ReceiverConfirmType = field.NewInt32(tableName, "receiver_confirm_type")
	_order.RefundAmount = field.NewInt64(tableName, "refund_amount")
	_order.RefundAt = field.NewInt64(tableName, "refund_at")
	_order.CancelAt = field.NewInt64(tableName, "cancel_at")
	_order.CancelType = field.NewInt32(tableName, "cancel_type")
	_order.CancelBy = field.NewInt64(tableName, "cancel_by")
	_order.CancelReason = field.NewString(tableName, "cancel_reason")
	_order.CreateAt = field.NewInt64(tableName, "create_at")
	_order.CreateBy = field.NewInt64(tableName, "create_by")

	_order.fillFieldMap()

	return _order
}

// order 订单表
type order struct {
	orderDo orderDo

	ALL                 field.Asterisk
	ID                  field.Int64
	OrderNo             field.String // 订单号
	UserID              field.Int64  // 用户ID
	Status              field.Int32  // -1：已取消，1: 待支付 2：已支付（待发货） 3：已退款  4：已发货 5：已签收 6：已收货
	OrderSource         field.Int32  // 1：用户下单  2：管理后台  3：系统赠送
	OrderAmount         field.Int64  // 订单金额=支付金额，单位分
	OrderOriginAmount   field.Int64  // 订单金额-商品原价，单位分
	PaymentAmount       field.Int64  // 支付金额-实际支付金额，单位分
	TradeNo             field.String // 支付平台订单号
	InnerTradeNo        field.String // 内部支付订单号
	OrderDesc           field.String // 订单描述
	PaymentAt           field.Int64  // 订单支付时间, 毫秒时间戳
	UserRemark          field.String // 用户备注
	ReceiverConfirmAt   field.Int64  // 确认收货时间
	ReceiverConfirmType field.Int32  // 确认收货方式 1：用户确认收货  99:发货10天自动确认收货
	RefundAmount        field.Int64  // 订单退款金额
	RefundAt            field.Int64  // 退款时间，毫秒时间戳
	CancelAt            field.Int64  // 取消时间，毫秒时间戳
	CancelType          field.Int32  // 1: 用户取消  2：客服取消  3: 超时取消
	CancelBy            field.Int64  // 取消人ID， 跟据取消类型判断是用户还是客服， -1为系统超时取消
	CancelReason        field.String // 取消理由
	CreateAt            field.Int64  // 订单创建时间，毫秒时间戳
	CreateBy            field.Int64  // 订单创建人ID，根据order_source判断是用户，还是客服ID，系统-1

	fieldMap map[string]field.Expr
}

func (o order) Table(newTableName string) *order {
	o.orderDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o order) As(alias string) *order {
	o.orderDo.DO = *(o.orderDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *order) updateTableName(table string) *order {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OrderNo = field.NewString(table, "order_no")
	o.UserID = field.NewInt64(table, "user_id")
	o.Status = field.NewInt32(table, "status")
	o.OrderSource = field.NewInt32(table, "order_source")
	o.OrderAmount = field.NewInt64(table, "order_amount")
	o.OrderOriginAmount = field.NewInt64(table, "order_origin_amount")
	o.PaymentAmount = field.NewInt64(table, "payment_amount")
	o.TradeNo = field.NewString(table, "trade_no")
	o.InnerTradeNo = field.NewString(table, "inner_trade_no")
	o.OrderDesc = field.NewString(table, "order_desc")
	o.PaymentAt = field.NewInt64(table, "payment_at")
	o.UserRemark = field.NewString(table, "user_remark")
	o.ReceiverConfirmAt = field.NewInt64(table, "receiver_confirm_at")
	o.ReceiverConfirmType = field.NewInt32(table, "receiver_confirm_type")
	o.RefundAmount = field.NewInt64(table, "refund_amount")
	o.RefundAt = field.NewInt64(table, "refund_at")
	o.CancelAt = field.NewInt64(table, "cancel_at")
	o.CancelType = field.NewInt32(table, "cancel_type")
	o.CancelBy = field.NewInt64(table, "cancel_by")
	o.CancelReason = field.NewString(table, "cancel_reason")
	o.CreateAt = field.NewInt64(table, "create_at")
	o.CreateBy = field.NewInt64(table, "create_by")

	o.fillFieldMap()

	return o
}

func (o *order) WithContext(ctx context.Context) *orderDo { return o.orderDo.WithContext(ctx) }

func (o order) TableName() string { return o.orderDo.TableName() }

func (o order) Alias() string { return o.orderDo.Alias() }

func (o order) Columns(cols ...field.Expr) gen.Columns { return o.orderDo.Columns(cols...) }

func (o *order) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *order) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 23)
	o.fieldMap["id"] = o.ID
	o.fieldMap["order_no"] = o.OrderNo
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["status"] = o.Status
	o.fieldMap["order_source"] = o.OrderSource
	o.fieldMap["order_amount"] = o.OrderAmount
	o.fieldMap["order_origin_amount"] = o.OrderOriginAmount
	o.fieldMap["payment_amount"] = o.PaymentAmount
	o.fieldMap["trade_no"] = o.TradeNo
	o.fieldMap["inner_trade_no"] = o.InnerTradeNo
	o.fieldMap["order_desc"] = o.OrderDesc
	o.fieldMap["payment_at"] = o.PaymentAt
	o.fieldMap["user_remark"] = o.UserRemark
	o.fieldMap["receiver_confirm_at"] = o.ReceiverConfirmAt
	o.fieldMap["receiver_confirm_type"] = o.ReceiverConfirmType
	o.fieldMap["refund_amount"] = o.RefundAmount
	o.fieldMap["refund_at"] = o.RefundAt
	o.fieldMap["cancel_at"] = o.CancelAt
	o.fieldMap["cancel_type"] = o.CancelType
	o.fieldMap["cancel_by"] = o.CancelBy
	o.fieldMap["cancel_reason"] = o.CancelReason
	o.fieldMap["create_at"] = o.CreateAt
	o.fieldMap["create_by"] = o.CreateBy
}

func (o order) clone(db *gorm.DB) order {
	o.orderDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o order) replaceDB(db *gorm.DB) order {
	o.orderDo.ReplaceDB(db)
	return o
}

type orderDo struct{ gen.DO }

func (o orderDo) Debug() *orderDo {
	return o.withDO(o.DO.Debug())
}

func (o orderDo) WithContext(ctx context.Context) *orderDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderDo) ReadDB() *orderDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderDo) WriteDB() *orderDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderDo) Session(config *gorm.Session) *orderDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderDo) Clauses(conds ...clause.Expression) *orderDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderDo) Returning(value interface{}, columns ...string) *orderDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderDo) Not(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderDo) Or(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderDo) Select(conds ...field.Expr) *orderDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderDo) Where(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderDo) Order(conds ...field.Expr) *orderDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderDo) Distinct(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderDo) Omit(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderDo) Join(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderDo) Group(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderDo) Having(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderDo) Limit(limit int) *orderDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderDo) Offset(offset int) *orderDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderDo) Unscoped() *orderDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderDo) Create(values ...*model.Order) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderDo) CreateInBatches(values []*model.Order, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderDo) Save(values ...*model.Order) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderDo) First() (*model.Order, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Take() (*model.Order, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Last() (*model.Order, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Find() ([]*model.Order, error) {
	result, err := o.DO.Find()
	return result.([]*model.Order), err
}

func (o orderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Order, err error) {
	buf := make([]*model.Order, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderDo) FindInBatches(result *[]*model.Order, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderDo) Attrs(attrs ...field.AssignExpr) *orderDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderDo) Assign(attrs ...field.AssignExpr) *orderDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderDo) Joins(fields ...field.RelationField) *orderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderDo) Preload(fields ...field.RelationField) *orderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderDo) FirstOrInit() (*model.Order, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) FirstOrCreate() (*model.Order, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) FindByPage(offset int, limit int) (result []*model.Order, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderDo) Delete(models ...*model.Order) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderDo) withDO(do gen.Dao) *orderDo {
	o.DO = *do.(*gen.DO)
	return o
}
