// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newSmsTemplate(db *gorm.DB, opts ...gen.DOOption) smsTemplate {
	_smsTemplate := smsTemplate{}

	_smsTemplate.smsTemplateDo.UseDB(db, opts...)
	_smsTemplate.smsTemplateDo.UseModel(&model.SmsTemplate{})

	tableName := _smsTemplate.smsTemplateDo.TableName()
	_smsTemplate.ALL = field.NewAsterisk(tableName)
	_smsTemplate.ID = field.NewInt64(tableName, "id")
	_smsTemplate.SceneCode = field.NewString(tableName, "scene_code")
	_smsTemplate.SignName = field.NewString(tableName, "sign_name")
	_smsTemplate.PlatformTmplID = field.NewInt32(tableName, "platform_tmpl_id")
	_smsTemplate.TmplStr = field.NewString(tableName, "tmpl_str")
	_smsTemplate.Status = field.NewInt32(tableName, "status")
	_smsTemplate.CreateAt = field.NewTime(tableName, "create_at")
	_smsTemplate.UpdateAt = field.NewTime(tableName, "update_at")
	_smsTemplate.AdminUserID = field.NewInt64(tableName, "admin_user_id")
	_smsTemplate.Platform = field.NewString(tableName, "platform")

	_smsTemplate.fillFieldMap()

	return _smsTemplate
}

// smsTemplate 短信模板表
type smsTemplate struct {
	smsTemplateDo smsTemplateDo

	ALL            field.Asterisk
	ID             field.Int64
	SceneCode      field.String // 场景编码，有意义的英文字符串
	SignName       field.String // 短信签名，需去短信平台申请审核
	PlatformTmplID field.Int32  // 第三方短信平台的模版ID
	TmplStr        field.String // 短信模版内容，该字符串内容可先内置，后续可开放管理后台修改
	Status         field.Int32  // 默认1：正常 -1：禁用
	CreateAt       field.Time
	UpdateAt       field.Time
	AdminUserID    field.Int64  // 管理后台admin_user_id
	Platform       field.String // tencent, ronglian

	fieldMap map[string]field.Expr
}

func (s smsTemplate) Table(newTableName string) *smsTemplate {
	s.smsTemplateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s smsTemplate) As(alias string) *smsTemplate {
	s.smsTemplateDo.DO = *(s.smsTemplateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *smsTemplate) updateTableName(table string) *smsTemplate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SceneCode = field.NewString(table, "scene_code")
	s.SignName = field.NewString(table, "sign_name")
	s.PlatformTmplID = field.NewInt32(table, "platform_tmpl_id")
	s.TmplStr = field.NewString(table, "tmpl_str")
	s.Status = field.NewInt32(table, "status")
	s.CreateAt = field.NewTime(table, "create_at")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.AdminUserID = field.NewInt64(table, "admin_user_id")
	s.Platform = field.NewString(table, "platform")

	s.fillFieldMap()

	return s
}

func (s *smsTemplate) WithContext(ctx context.Context) *smsTemplateDo {
	return s.smsTemplateDo.WithContext(ctx)
}

func (s smsTemplate) TableName() string { return s.smsTemplateDo.TableName() }

func (s smsTemplate) Alias() string { return s.smsTemplateDo.Alias() }

func (s smsTemplate) Columns(cols ...field.Expr) gen.Columns { return s.smsTemplateDo.Columns(cols...) }

func (s *smsTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *smsTemplate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["scene_code"] = s.SceneCode
	s.fieldMap["sign_name"] = s.SignName
	s.fieldMap["platform_tmpl_id"] = s.PlatformTmplID
	s.fieldMap["tmpl_str"] = s.TmplStr
	s.fieldMap["status"] = s.Status
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["admin_user_id"] = s.AdminUserID
	s.fieldMap["platform"] = s.Platform
}

func (s smsTemplate) clone(db *gorm.DB) smsTemplate {
	s.smsTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s smsTemplate) replaceDB(db *gorm.DB) smsTemplate {
	s.smsTemplateDo.ReplaceDB(db)
	return s
}

type smsTemplateDo struct{ gen.DO }

func (s smsTemplateDo) Debug() *smsTemplateDo {
	return s.withDO(s.DO.Debug())
}

func (s smsTemplateDo) WithContext(ctx context.Context) *smsTemplateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s smsTemplateDo) ReadDB() *smsTemplateDo {
	return s.Clauses(dbresolver.Read)
}

func (s smsTemplateDo) WriteDB() *smsTemplateDo {
	return s.Clauses(dbresolver.Write)
}

func (s smsTemplateDo) Session(config *gorm.Session) *smsTemplateDo {
	return s.withDO(s.DO.Session(config))
}

func (s smsTemplateDo) Clauses(conds ...clause.Expression) *smsTemplateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s smsTemplateDo) Returning(value interface{}, columns ...string) *smsTemplateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s smsTemplateDo) Not(conds ...gen.Condition) *smsTemplateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s smsTemplateDo) Or(conds ...gen.Condition) *smsTemplateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s smsTemplateDo) Select(conds ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s smsTemplateDo) Where(conds ...gen.Condition) *smsTemplateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s smsTemplateDo) Order(conds ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s smsTemplateDo) Distinct(cols ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s smsTemplateDo) Omit(cols ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s smsTemplateDo) Join(table schema.Tabler, on ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s smsTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s smsTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s smsTemplateDo) Group(cols ...field.Expr) *smsTemplateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s smsTemplateDo) Having(conds ...gen.Condition) *smsTemplateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s smsTemplateDo) Limit(limit int) *smsTemplateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s smsTemplateDo) Offset(offset int) *smsTemplateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s smsTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *smsTemplateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s smsTemplateDo) Unscoped() *smsTemplateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s smsTemplateDo) Create(values ...*model.SmsTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s smsTemplateDo) CreateInBatches(values []*model.SmsTemplate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s smsTemplateDo) Save(values ...*model.SmsTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s smsTemplateDo) First() (*model.SmsTemplate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsTemplate), nil
	}
}

func (s smsTemplateDo) Take() (*model.SmsTemplate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsTemplate), nil
	}
}

func (s smsTemplateDo) Last() (*model.SmsTemplate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsTemplate), nil
	}
}

func (s smsTemplateDo) Find() ([]*model.SmsTemplate, error) {
	result, err := s.DO.Find()
	return result.([]*model.SmsTemplate), err
}

func (s smsTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SmsTemplate, err error) {
	buf := make([]*model.SmsTemplate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s smsTemplateDo) FindInBatches(result *[]*model.SmsTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s smsTemplateDo) Attrs(attrs ...field.AssignExpr) *smsTemplateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s smsTemplateDo) Assign(attrs ...field.AssignExpr) *smsTemplateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s smsTemplateDo) Joins(fields ...field.RelationField) *smsTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s smsTemplateDo) Preload(fields ...field.RelationField) *smsTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s smsTemplateDo) FirstOrInit() (*model.SmsTemplate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsTemplate), nil
	}
}

func (s smsTemplateDo) FirstOrCreate() (*model.SmsTemplate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsTemplate), nil
	}
}

func (s smsTemplateDo) FindByPage(offset int, limit int) (result []*model.SmsTemplate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s smsTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s smsTemplateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s smsTemplateDo) Delete(models ...*model.SmsTemplate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *smsTemplateDo) withDO(do gen.Dao) *smsTemplateDo {
	s.DO = *do.(*gen.DO)
	return s
}
