// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppUser = "app_user"

// AppUser 应用用户表
type AppUser struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增（无实际用途）" json:"id"`                // 自增（无实际用途）
	UserID   int64     `gorm:"column:user_id;not null;comment:全局用户id,user表主键" json:"user_id"`                      // 全局用户id,user表主键
	AppCode  int32     `gorm:"column:app_code;not null;comment:1000=公众号，1001=小程序， 其他进行扩展，固定值不能变更" json:"app_code"` // 1000=公众号，1001=小程序， 其他进行扩展，固定值不能变更
	OpenID   string    `gorm:"column:open_id;not null;comment:当前存储微信应用的openid" json:"open_id"`                     // 当前存储微信应用的openid
	Status   int32     `gorm:"column:status;not null;default:1;comment:默认1：正常 -1：禁用" json:"status"`                // 默认1：正常 -1：禁用
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName AppUser's table name
func (*AppUser) TableName() string {
	return TableNameAppUser
}
