// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "orders"

// Order 订单表
type Order struct {
	ID                  int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderNo             string  `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                                                     // 订单号
	UserID              int64   `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                                      // 用户ID
	Status              int32   `gorm:"column:status;not null;default:1;comment:-1：已取消，1: 待支付 2：已支付（待发货） 3：已退款  4：已发货 5：已签收 6：已收货" json:"status"` // -1：已取消，1: 待支付 2：已支付（待发货） 3：已退款  4：已发货 5：已签收 6：已收货
	OrderSource         int32   `gorm:"column:order_source;not null;comment:1：用户下单  2：管理后台  3：系统赠送" json:"order_source"`                          // 1：用户下单  2：管理后台  3：系统赠送
	OrderAmount         int64   `gorm:"column:order_amount;not null;comment:订单金额=支付金额，单位分" json:"order_amount"`                                   // 订单金额=支付金额，单位分
	OrderOriginAmount   int64   `gorm:"column:order_origin_amount;not null;comment:订单金额-商品原价，单位分" json:"order_origin_amount"`                     // 订单金额-商品原价，单位分
	PaymentAmount       int64   `gorm:"column:payment_amount;not null;comment:支付金额-实际支付金额，单位分" json:"payment_amount"`                             // 支付金额-实际支付金额，单位分
	TradeNo             string  `gorm:"column:trade_no;not null;comment:支付平台订单号" json:"trade_no"`                                                 // 支付平台订单号
	InnerTradeNo        string  `gorm:"column:inner_trade_no;not null;comment:内部支付订单号" json:"inner_trade_no"`                                     // 内部支付订单号
	OrderDesc           string  `gorm:"column:order_desc;not null;comment:订单描述" json:"order_desc"`                                                // 订单描述
	PaymentAt           int64   `gorm:"column:payment_at;not null;comment:订单支付时间, 毫秒时间戳" json:"payment_at"`                                       // 订单支付时间, 毫秒时间戳
	UserRemark          string  `gorm:"column:user_remark;not null;comment:用户备注" json:"user_remark"`                                              // 用户备注
	ReceiverConfirmAt   *int64  `gorm:"column:receiver_confirm_at;comment:确认收货时间" json:"receiver_confirm_at"`                                     // 确认收货时间
	ReceiverConfirmType *int32  `gorm:"column:receiver_confirm_type;comment:确认收货方式 1：用户确认收货  99:发货10天自动确认收货" json:"receiver_confirm_type"`        // 确认收货方式 1：用户确认收货  99:发货10天自动确认收货
	RefundAmount        int64   `gorm:"column:refund_amount;not null;comment:订单退款金额" json:"refund_amount"`                                        // 订单退款金额
	RefundAt            *int64  `gorm:"column:refund_at;comment:退款时间，毫秒时间戳" json:"refund_at"`                                                     // 退款时间，毫秒时间戳
	CancelAt            *int64  `gorm:"column:cancel_at;comment:取消时间，毫秒时间戳" json:"cancel_at"`                                                     // 取消时间，毫秒时间戳
	CancelType          *int32  `gorm:"column:cancel_type;comment:1: 用户取消  2：客服取消  3: 超时取消" json:"cancel_type"`                                   // 1: 用户取消  2：客服取消  3: 超时取消
	CancelBy            *int64  `gorm:"column:cancel_by;comment:取消人ID， 跟据取消类型判断是用户还是客服， -1为系统超时取消" json:"cancel_by"`                              // 取消人ID， 跟据取消类型判断是用户还是客服， -1为系统超时取消
	CancelReason        *string `gorm:"column:cancel_reason;comment:取消理由" json:"cancel_reason"`                                                   // 取消理由
	CreateAt            int64   `gorm:"column:create_at;not null;comment:订单创建时间，毫秒时间戳" json:"create_at"`                                          // 订单创建时间，毫秒时间戳
	CreateBy            int64   `gorm:"column:create_by;not null;comment:订单创建人ID，根据order_source判断是用户，还是客服ID，系统-1" json:"create_by"`               // 订单创建人ID，根据order_source判断是用户，还是客服ID，系统-1
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
