// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsTemplate = "sms_template"

// SmsTemplate 短信模板表
type SmsTemplate struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SceneCode      string    `gorm:"column:scene_code;not null;comment:场景编码，有意义的英文字符串" json:"scene_code"`            // 场景编码，有意义的英文字符串
	SignName       string    `gorm:"column:sign_name;not null;comment:短信签名，需去短信平台申请审核" json:"sign_name"`             // 短信签名，需去短信平台申请审核
	PlatformTmplID int32     `gorm:"column:platform_tmpl_id;not null;comment:第三方短信平台的模版ID" json:"platform_tmpl_id"`  // 第三方短信平台的模版ID
	TmplStr        string    `gorm:"column:tmpl_str;not null;comment:短信模版内容，该字符串内容可先内置，后续可开放管理后台修改" json:"tmpl_str"` // 短信模版内容，该字符串内容可先内置，后续可开放管理后台修改
	Status         int32     `gorm:"column:status;not null;default:1;comment:默认1：正常 -1：禁用" json:"status"`            // 默认1：正常 -1：禁用
	CreateAt       time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt       time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	AdminUserID    int64     `gorm:"column:admin_user_id;not null;comment:管理后台admin_user_id" json:"admin_user_id"` // 管理后台admin_user_id
	Platform       string    `gorm:"column:platform;not null;comment:tencent, ronglian" json:"platform"`           // tencent, ronglian
}

// TableName SmsTemplate's table name
func (*SmsTemplate) TableName() string {
	return TableNameSmsTemplate
}
