// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCourseGood = "user_course_goods"

// UserCourseGood 用户购买的课程列表
type UserCourseGood struct {
	ID                int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID            int64 `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                               // 用户ID
	OrderID           int64 `gorm:"column:order_id;not null;comment:订单ID" json:"order_id"`                             // 订单ID
	GoodsID           int64 `gorm:"column:goods_id;not null;comment:商品ID" json:"goods_id"`                             // 商品ID
	GoodsType         int32 `gorm:"column:goods_type;not null;comment:1.课程商品" json:"goods_type"`                       // 1.课程商品
	BuyTime           int64 `gorm:"column:buy_time;not null;comment:购买时间" json:"buy_time"`                             // 购买时间
	ServiceExpireTime int64 `gorm:"column:service_expire_time;not null;comment:fudao 到期时间" json:"service_expire_time"` // fudao 到期时间
}

// TableName UserCourseGood's table name
func (*UserCourseGood) TableName() string {
	return TableNameUserCourseGood
}
