// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newAdminUserRole(db *gorm.DB, opts ...gen.DOOption) adminUserRole {
	_adminUserRole := adminUserRole{}

	_adminUserRole.adminUserRoleDo.UseDB(db, opts...)
	_adminUserRole.adminUserRoleDo.UseModel(&model.AdminUserRole{})

	tableName := _adminUserRole.adminUserRoleDo.TableName()
	_adminUserRole.ALL = field.NewAsterisk(tableName)
	_adminUserRole.ID = field.NewInt64(tableName, "id")
	_adminUserRole.AdminUserID = field.NewInt64(tableName, "admin_user_id")
	_adminUserRole.RoleID = field.NewInt64(tableName, "role_id")
	_adminUserRole.UpdateAt = field.NewTime(tableName, "update_at")
	_adminUserRole.UpdateBy = field.NewInt64(tableName, "update_by")

	_adminUserRole.fillFieldMap()

	return _adminUserRole
}

// adminUserRole 管理员角色表
type adminUserRole struct {
	adminUserRoleDo adminUserRoleDo

	ALL         field.Asterisk
	ID          field.Int64
	AdminUserID field.Int64 // 管理员ID
	RoleID      field.Int64 // 角色ID
	UpdateAt    field.Time
	UpdateBy    field.Int64

	fieldMap map[string]field.Expr
}

func (a adminUserRole) Table(newTableName string) *adminUserRole {
	a.adminUserRoleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminUserRole) As(alias string) *adminUserRole {
	a.adminUserRoleDo.DO = *(a.adminUserRoleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminUserRole) updateTableName(table string) *adminUserRole {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.AdminUserID = field.NewInt64(table, "admin_user_id")
	a.RoleID = field.NewInt64(table, "role_id")
	a.UpdateAt = field.NewTime(table, "update_at")
	a.UpdateBy = field.NewInt64(table, "update_by")

	a.fillFieldMap()

	return a
}

func (a *adminUserRole) WithContext(ctx context.Context) *adminUserRoleDo {
	return a.adminUserRoleDo.WithContext(ctx)
}

func (a adminUserRole) TableName() string { return a.adminUserRoleDo.TableName() }

func (a adminUserRole) Alias() string { return a.adminUserRoleDo.Alias() }

func (a adminUserRole) Columns(cols ...field.Expr) gen.Columns {
	return a.adminUserRoleDo.Columns(cols...)
}

func (a *adminUserRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminUserRole) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["admin_user_id"] = a.AdminUserID
	a.fieldMap["role_id"] = a.RoleID
	a.fieldMap["update_at"] = a.UpdateAt
	a.fieldMap["update_by"] = a.UpdateBy
}

func (a adminUserRole) clone(db *gorm.DB) adminUserRole {
	a.adminUserRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminUserRole) replaceDB(db *gorm.DB) adminUserRole {
	a.adminUserRoleDo.ReplaceDB(db)
	return a
}

type adminUserRoleDo struct{ gen.DO }

func (a adminUserRoleDo) Debug() *adminUserRoleDo {
	return a.withDO(a.DO.Debug())
}

func (a adminUserRoleDo) WithContext(ctx context.Context) *adminUserRoleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminUserRoleDo) ReadDB() *adminUserRoleDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminUserRoleDo) WriteDB() *adminUserRoleDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminUserRoleDo) Session(config *gorm.Session) *adminUserRoleDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminUserRoleDo) Clauses(conds ...clause.Expression) *adminUserRoleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminUserRoleDo) Returning(value interface{}, columns ...string) *adminUserRoleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminUserRoleDo) Not(conds ...gen.Condition) *adminUserRoleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminUserRoleDo) Or(conds ...gen.Condition) *adminUserRoleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminUserRoleDo) Select(conds ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminUserRoleDo) Where(conds ...gen.Condition) *adminUserRoleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminUserRoleDo) Order(conds ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminUserRoleDo) Distinct(cols ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminUserRoleDo) Omit(cols ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminUserRoleDo) Join(table schema.Tabler, on ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminUserRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminUserRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminUserRoleDo) Group(cols ...field.Expr) *adminUserRoleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminUserRoleDo) Having(conds ...gen.Condition) *adminUserRoleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminUserRoleDo) Limit(limit int) *adminUserRoleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminUserRoleDo) Offset(offset int) *adminUserRoleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminUserRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *adminUserRoleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminUserRoleDo) Unscoped() *adminUserRoleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminUserRoleDo) Create(values ...*model.AdminUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminUserRoleDo) CreateInBatches(values []*model.AdminUserRole, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminUserRoleDo) Save(values ...*model.AdminUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminUserRoleDo) First() (*model.AdminUserRole, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminUserRole), nil
	}
}

func (a adminUserRoleDo) Take() (*model.AdminUserRole, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminUserRole), nil
	}
}

func (a adminUserRoleDo) Last() (*model.AdminUserRole, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminUserRole), nil
	}
}

func (a adminUserRoleDo) Find() ([]*model.AdminUserRole, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminUserRole), err
}

func (a adminUserRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminUserRole, err error) {
	buf := make([]*model.AdminUserRole, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminUserRoleDo) FindInBatches(result *[]*model.AdminUserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminUserRoleDo) Attrs(attrs ...field.AssignExpr) *adminUserRoleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminUserRoleDo) Assign(attrs ...field.AssignExpr) *adminUserRoleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminUserRoleDo) Joins(fields ...field.RelationField) *adminUserRoleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminUserRoleDo) Preload(fields ...field.RelationField) *adminUserRoleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminUserRoleDo) FirstOrInit() (*model.AdminUserRole, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminUserRole), nil
	}
}

func (a adminUserRoleDo) FirstOrCreate() (*model.AdminUserRole, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminUserRole), nil
	}
}

func (a adminUserRoleDo) FindByPage(offset int, limit int) (result []*model.AdminUserRole, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminUserRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminUserRoleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminUserRoleDo) Delete(models ...*model.AdminUserRole) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminUserRoleDo) withDO(do gen.Dao) *adminUserRoleDo {
	a.DO = *do.(*gen.DO)
	return a
}
