// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newCourseLesson(db *gorm.DB, opts ...gen.DOOption) courseLesson {
	_courseLesson := courseLesson{}

	_courseLesson.courseLessonDo.UseDB(db, opts...)
	_courseLesson.courseLessonDo.UseModel(&model.CourseLesson{})

	tableName := _courseLesson.courseLessonDo.TableName()
	_courseLesson.ALL = field.NewAsterisk(tableName)
	_courseLesson.ID = field.NewInt64(tableName, "id")
	_courseLesson.GoodsID = field.NewInt64(tableName, "goods_id")
	_courseLesson.CatalogID = field.NewInt64(tableName, "catalog_id")
	_courseLesson.Name = field.NewString(tableName, "name")
	_courseLesson.EnableTrial = field.NewInt32(tableName, "enable_trial")
	_courseLesson.Status = field.NewInt32(tableName, "status")
	_courseLesson.VideoKey = field.NewString(tableName, "video_key")
	_courseLesson.Detail = field.NewString(tableName, "detail")
	_courseLesson.Homework = field.NewString(tableName, "homework")
	_courseLesson.Sort = field.NewInt32(tableName, "sort")
	_courseLesson.ShowTime = field.NewTime(tableName, "show_time")
	_courseLesson.Attachments = field.NewString(tableName, "attachments")
	_courseLesson.UpdateAt = field.NewTime(tableName, "update_at")
	_courseLesson.UpdateBy = field.NewInt64(tableName, "update_by")

	_courseLesson.fillFieldMap()

	return _courseLesson
}

// courseLesson 课程课时表
type courseLesson struct {
	courseLessonDo courseLessonDo

	ALL         field.Asterisk
	ID          field.Int64
	GoodsID     field.Int64
	CatalogID   field.Int64
	Name        field.String // 课时名称
	EnableTrial field.Int32  // 1:试听 其他值表示非试听
	Status      field.Int32  // 1:启用 -1：禁用
	VideoKey    field.String // 文件key
	Detail      field.String // 课时详情
	Homework    field.String // 课后练习
	Sort        field.Int32
	ShowTime    field.Time   // 课时可见时间
	Attachments field.String // 课时课件文件列表[{"file_key": "", "file_name": "", "file_type": ""}]
	UpdateAt    field.Time
	UpdateBy    field.Int64

	fieldMap map[string]field.Expr
}

func (c courseLesson) Table(newTableName string) *courseLesson {
	c.courseLessonDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c courseLesson) As(alias string) *courseLesson {
	c.courseLessonDo.DO = *(c.courseLessonDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *courseLesson) updateTableName(table string) *courseLesson {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.GoodsID = field.NewInt64(table, "goods_id")
	c.CatalogID = field.NewInt64(table, "catalog_id")
	c.Name = field.NewString(table, "name")
	c.EnableTrial = field.NewInt32(table, "enable_trial")
	c.Status = field.NewInt32(table, "status")
	c.VideoKey = field.NewString(table, "video_key")
	c.Detail = field.NewString(table, "detail")
	c.Homework = field.NewString(table, "homework")
	c.Sort = field.NewInt32(table, "sort")
	c.ShowTime = field.NewTime(table, "show_time")
	c.Attachments = field.NewString(table, "attachments")
	c.UpdateAt = field.NewTime(table, "update_at")
	c.UpdateBy = field.NewInt64(table, "update_by")

	c.fillFieldMap()

	return c
}

func (c *courseLesson) WithContext(ctx context.Context) *courseLessonDo {
	return c.courseLessonDo.WithContext(ctx)
}

func (c courseLesson) TableName() string { return c.courseLessonDo.TableName() }

func (c courseLesson) Alias() string { return c.courseLessonDo.Alias() }

func (c courseLesson) Columns(cols ...field.Expr) gen.Columns {
	return c.courseLessonDo.Columns(cols...)
}

func (c *courseLesson) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *courseLesson) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["goods_id"] = c.GoodsID
	c.fieldMap["catalog_id"] = c.CatalogID
	c.fieldMap["name"] = c.Name
	c.fieldMap["enable_trial"] = c.EnableTrial
	c.fieldMap["status"] = c.Status
	c.fieldMap["video_key"] = c.VideoKey
	c.fieldMap["detail"] = c.Detail
	c.fieldMap["homework"] = c.Homework
	c.fieldMap["sort"] = c.Sort
	c.fieldMap["show_time"] = c.ShowTime
	c.fieldMap["attachments"] = c.Attachments
	c.fieldMap["update_at"] = c.UpdateAt
	c.fieldMap["update_by"] = c.UpdateBy
}

func (c courseLesson) clone(db *gorm.DB) courseLesson {
	c.courseLessonDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c courseLesson) replaceDB(db *gorm.DB) courseLesson {
	c.courseLessonDo.ReplaceDB(db)
	return c
}

type courseLessonDo struct{ gen.DO }

func (c courseLessonDo) Debug() *courseLessonDo {
	return c.withDO(c.DO.Debug())
}

func (c courseLessonDo) WithContext(ctx context.Context) *courseLessonDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c courseLessonDo) ReadDB() *courseLessonDo {
	return c.Clauses(dbresolver.Read)
}

func (c courseLessonDo) WriteDB() *courseLessonDo {
	return c.Clauses(dbresolver.Write)
}

func (c courseLessonDo) Session(config *gorm.Session) *courseLessonDo {
	return c.withDO(c.DO.Session(config))
}

func (c courseLessonDo) Clauses(conds ...clause.Expression) *courseLessonDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c courseLessonDo) Returning(value interface{}, columns ...string) *courseLessonDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c courseLessonDo) Not(conds ...gen.Condition) *courseLessonDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c courseLessonDo) Or(conds ...gen.Condition) *courseLessonDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c courseLessonDo) Select(conds ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c courseLessonDo) Where(conds ...gen.Condition) *courseLessonDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c courseLessonDo) Order(conds ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c courseLessonDo) Distinct(cols ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c courseLessonDo) Omit(cols ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c courseLessonDo) Join(table schema.Tabler, on ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c courseLessonDo) LeftJoin(table schema.Tabler, on ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c courseLessonDo) RightJoin(table schema.Tabler, on ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c courseLessonDo) Group(cols ...field.Expr) *courseLessonDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c courseLessonDo) Having(conds ...gen.Condition) *courseLessonDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c courseLessonDo) Limit(limit int) *courseLessonDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c courseLessonDo) Offset(offset int) *courseLessonDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c courseLessonDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *courseLessonDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c courseLessonDo) Unscoped() *courseLessonDo {
	return c.withDO(c.DO.Unscoped())
}

func (c courseLessonDo) Create(values ...*model.CourseLesson) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c courseLessonDo) CreateInBatches(values []*model.CourseLesson, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c courseLessonDo) Save(values ...*model.CourseLesson) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c courseLessonDo) First() (*model.CourseLesson, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Take() (*model.CourseLesson, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Last() (*model.CourseLesson, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Find() ([]*model.CourseLesson, error) {
	result, err := c.DO.Find()
	return result.([]*model.CourseLesson), err
}

func (c courseLessonDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CourseLesson, err error) {
	buf := make([]*model.CourseLesson, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c courseLessonDo) FindInBatches(result *[]*model.CourseLesson, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c courseLessonDo) Attrs(attrs ...field.AssignExpr) *courseLessonDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c courseLessonDo) Assign(attrs ...field.AssignExpr) *courseLessonDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c courseLessonDo) Joins(fields ...field.RelationField) *courseLessonDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c courseLessonDo) Preload(fields ...field.RelationField) *courseLessonDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c courseLessonDo) FirstOrInit() (*model.CourseLesson, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) FirstOrCreate() (*model.CourseLesson, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) FindByPage(offset int, limit int) (result []*model.CourseLesson, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c courseLessonDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c courseLessonDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c courseLessonDo) Delete(models ...*model.CourseLesson) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *courseLessonDo) withDO(do gen.Dao) *courseLessonDo {
	c.DO = *do.(*gen.DO)
	return c
}
