// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newCourseGood(db *gorm.DB, opts ...gen.DOOption) courseGood {
	_courseGood := courseGood{}

	_courseGood.courseGoodDo.UseDB(db, opts...)
	_courseGood.courseGoodDo.UseModel(&model.CourseGood{})

	tableName := _courseGood.courseGoodDo.TableName()
	_courseGood.ALL = field.NewAsterisk(tableName)
	_courseGood.ID = field.NewInt64(tableName, "id")
	_courseGood.Name = field.NewString(tableName, "name")
	_courseGood.CoverKey = field.NewString(tableName, "cover_key")
	_courseGood.IntroKey = field.NewString(tableName, "intro_key")
	_courseGood.Desc = field.NewString(tableName, "desc")
	_courseGood.GoodsPrice = field.NewInt64(tableName, "goods_price")
	_courseGood.ServiceTime = field.NewInt32(tableName, "service_time")
	_courseGood.SaleType = field.NewInt32(tableName, "sale_type")
	_courseGood.Status = field.NewInt32(tableName, "status")
	_courseGood.CreateAt = field.NewTime(tableName, "create_at")
	_courseGood.CreateBy = field.NewInt64(tableName, "create_by")
	_courseGood.UpdateAt = field.NewTime(tableName, "update_at")
	_courseGood.UpdateBy = field.NewInt64(tableName, "update_by")

	_courseGood.fillFieldMap()

	return _courseGood
}

// courseGood 课程商品表
type courseGood struct {
	courseGoodDo courseGoodDo

	ALL        field.Asterisk
	ID         field.Int64
	Name       field.String
	CoverKey   field.String // 封面图key
	IntroKey   field.String // 详情图key
	Desc       field.String
	GoodsPrice field.Int64 // 商品价格
	/*
		辅导服务时长
		1：一个月 2：三个月 3：半年 4：一年
	*/
	ServiceTime field.Int32
	SaleType    field.Int32 // 1：免费 2：收费
	Status      field.Int32 // -1：下架 1：上架
	CreateAt    field.Time
	CreateBy    field.Int64
	UpdateAt    field.Time
	UpdateBy    field.Int64

	fieldMap map[string]field.Expr
}

func (c courseGood) Table(newTableName string) *courseGood {
	c.courseGoodDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c courseGood) As(alias string) *courseGood {
	c.courseGoodDo.DO = *(c.courseGoodDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *courseGood) updateTableName(table string) *courseGood {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.CoverKey = field.NewString(table, "cover_key")
	c.IntroKey = field.NewString(table, "intro_key")
	c.Desc = field.NewString(table, "desc")
	c.GoodsPrice = field.NewInt64(table, "goods_price")
	c.ServiceTime = field.NewInt32(table, "service_time")
	c.SaleType = field.NewInt32(table, "sale_type")
	c.Status = field.NewInt32(table, "status")
	c.CreateAt = field.NewTime(table, "create_at")
	c.CreateBy = field.NewInt64(table, "create_by")
	c.UpdateAt = field.NewTime(table, "update_at")
	c.UpdateBy = field.NewInt64(table, "update_by")

	c.fillFieldMap()

	return c
}

func (c *courseGood) WithContext(ctx context.Context) *courseGoodDo {
	return c.courseGoodDo.WithContext(ctx)
}

func (c courseGood) TableName() string { return c.courseGoodDo.TableName() }

func (c courseGood) Alias() string { return c.courseGoodDo.Alias() }

func (c courseGood) Columns(cols ...field.Expr) gen.Columns { return c.courseGoodDo.Columns(cols...) }

func (c *courseGood) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *courseGood) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 13)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["cover_key"] = c.CoverKey
	c.fieldMap["intro_key"] = c.IntroKey
	c.fieldMap["desc"] = c.Desc
	c.fieldMap["goods_price"] = c.GoodsPrice
	c.fieldMap["service_time"] = c.ServiceTime
	c.fieldMap["sale_type"] = c.SaleType
	c.fieldMap["status"] = c.Status
	c.fieldMap["create_at"] = c.CreateAt
	c.fieldMap["create_by"] = c.CreateBy
	c.fieldMap["update_at"] = c.UpdateAt
	c.fieldMap["update_by"] = c.UpdateBy
}

func (c courseGood) clone(db *gorm.DB) courseGood {
	c.courseGoodDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c courseGood) replaceDB(db *gorm.DB) courseGood {
	c.courseGoodDo.ReplaceDB(db)
	return c
}

type courseGoodDo struct{ gen.DO }

func (c courseGoodDo) Debug() *courseGoodDo {
	return c.withDO(c.DO.Debug())
}

func (c courseGoodDo) WithContext(ctx context.Context) *courseGoodDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c courseGoodDo) ReadDB() *courseGoodDo {
	return c.Clauses(dbresolver.Read)
}

func (c courseGoodDo) WriteDB() *courseGoodDo {
	return c.Clauses(dbresolver.Write)
}

func (c courseGoodDo) Session(config *gorm.Session) *courseGoodDo {
	return c.withDO(c.DO.Session(config))
}

func (c courseGoodDo) Clauses(conds ...clause.Expression) *courseGoodDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c courseGoodDo) Returning(value interface{}, columns ...string) *courseGoodDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c courseGoodDo) Not(conds ...gen.Condition) *courseGoodDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c courseGoodDo) Or(conds ...gen.Condition) *courseGoodDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c courseGoodDo) Select(conds ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c courseGoodDo) Where(conds ...gen.Condition) *courseGoodDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c courseGoodDo) Order(conds ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c courseGoodDo) Distinct(cols ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c courseGoodDo) Omit(cols ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c courseGoodDo) Join(table schema.Tabler, on ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c courseGoodDo) LeftJoin(table schema.Tabler, on ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c courseGoodDo) RightJoin(table schema.Tabler, on ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c courseGoodDo) Group(cols ...field.Expr) *courseGoodDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c courseGoodDo) Having(conds ...gen.Condition) *courseGoodDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c courseGoodDo) Limit(limit int) *courseGoodDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c courseGoodDo) Offset(offset int) *courseGoodDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c courseGoodDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *courseGoodDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c courseGoodDo) Unscoped() *courseGoodDo {
	return c.withDO(c.DO.Unscoped())
}

func (c courseGoodDo) Create(values ...*model.CourseGood) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c courseGoodDo) CreateInBatches(values []*model.CourseGood, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c courseGoodDo) Save(values ...*model.CourseGood) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c courseGoodDo) First() (*model.CourseGood, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseGood), nil
	}
}

func (c courseGoodDo) Take() (*model.CourseGood, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseGood), nil
	}
}

func (c courseGoodDo) Last() (*model.CourseGood, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseGood), nil
	}
}

func (c courseGoodDo) Find() ([]*model.CourseGood, error) {
	result, err := c.DO.Find()
	return result.([]*model.CourseGood), err
}

func (c courseGoodDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CourseGood, err error) {
	buf := make([]*model.CourseGood, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c courseGoodDo) FindInBatches(result *[]*model.CourseGood, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c courseGoodDo) Attrs(attrs ...field.AssignExpr) *courseGoodDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c courseGoodDo) Assign(attrs ...field.AssignExpr) *courseGoodDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c courseGoodDo) Joins(fields ...field.RelationField) *courseGoodDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c courseGoodDo) Preload(fields ...field.RelationField) *courseGoodDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c courseGoodDo) FirstOrInit() (*model.CourseGood, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseGood), nil
	}
}

func (c courseGoodDo) FirstOrCreate() (*model.CourseGood, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseGood), nil
	}
}

func (c courseGoodDo) FindByPage(offset int, limit int) (result []*model.CourseGood, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c courseGoodDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c courseGoodDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c courseGoodDo) Delete(models ...*model.CourseGood) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *courseGoodDo) withDO(do gen.Dao) *courseGoodDo {
	c.DO = *do.(*gen.DO)
	return c
}
