// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newUserCourseGood(db *gorm.DB, opts ...gen.DOOption) userCourseGood {
	_userCourseGood := userCourseGood{}

	_userCourseGood.userCourseGoodDo.UseDB(db, opts...)
	_userCourseGood.userCourseGoodDo.UseModel(&model.UserCourseGood{})

	tableName := _userCourseGood.userCourseGoodDo.TableName()
	_userCourseGood.ALL = field.NewAsterisk(tableName)
	_userCourseGood.ID = field.NewInt64(tableName, "id")
	_userCourseGood.UserID = field.NewInt64(tableName, "user_id")
	_userCourseGood.OrderID = field.NewInt64(tableName, "order_id")
	_userCourseGood.GoodsID = field.NewInt64(tableName, "goods_id")
	_userCourseGood.GoodsType = field.NewInt32(tableName, "goods_type")
	_userCourseGood.BuyTime = field.NewInt64(tableName, "buy_time")
	_userCourseGood.ServiceExpireTime = field.NewInt64(tableName, "service_expire_time")

	_userCourseGood.fillFieldMap()

	return _userCourseGood
}

// userCourseGood 用户购买的课程列表
type userCourseGood struct {
	userCourseGoodDo userCourseGoodDo

	ALL               field.Asterisk
	ID                field.Int64
	UserID            field.Int64 // 用户ID
	OrderID           field.Int64 // 订单ID
	GoodsID           field.Int64 // 商品ID
	GoodsType         field.Int32 // 1.课程商品
	BuyTime           field.Int64 // 购买时间
	ServiceExpireTime field.Int64 // fudao 到期时间

	fieldMap map[string]field.Expr
}

func (u userCourseGood) Table(newTableName string) *userCourseGood {
	u.userCourseGoodDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userCourseGood) As(alias string) *userCourseGood {
	u.userCourseGoodDo.DO = *(u.userCourseGoodDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userCourseGood) updateTableName(table string) *userCourseGood {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.OrderID = field.NewInt64(table, "order_id")
	u.GoodsID = field.NewInt64(table, "goods_id")
	u.GoodsType = field.NewInt32(table, "goods_type")
	u.BuyTime = field.NewInt64(table, "buy_time")
	u.ServiceExpireTime = field.NewInt64(table, "service_expire_time")

	u.fillFieldMap()

	return u
}

func (u *userCourseGood) WithContext(ctx context.Context) *userCourseGoodDo {
	return u.userCourseGoodDo.WithContext(ctx)
}

func (u userCourseGood) TableName() string { return u.userCourseGoodDo.TableName() }

func (u userCourseGood) Alias() string { return u.userCourseGoodDo.Alias() }

func (u userCourseGood) Columns(cols ...field.Expr) gen.Columns {
	return u.userCourseGoodDo.Columns(cols...)
}

func (u *userCourseGood) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userCourseGood) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["order_id"] = u.OrderID
	u.fieldMap["goods_id"] = u.GoodsID
	u.fieldMap["goods_type"] = u.GoodsType
	u.fieldMap["buy_time"] = u.BuyTime
	u.fieldMap["service_expire_time"] = u.ServiceExpireTime
}

func (u userCourseGood) clone(db *gorm.DB) userCourseGood {
	u.userCourseGoodDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userCourseGood) replaceDB(db *gorm.DB) userCourseGood {
	u.userCourseGoodDo.ReplaceDB(db)
	return u
}

type userCourseGoodDo struct{ gen.DO }

func (u userCourseGoodDo) Debug() *userCourseGoodDo {
	return u.withDO(u.DO.Debug())
}

func (u userCourseGoodDo) WithContext(ctx context.Context) *userCourseGoodDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userCourseGoodDo) ReadDB() *userCourseGoodDo {
	return u.Clauses(dbresolver.Read)
}

func (u userCourseGoodDo) WriteDB() *userCourseGoodDo {
	return u.Clauses(dbresolver.Write)
}

func (u userCourseGoodDo) Session(config *gorm.Session) *userCourseGoodDo {
	return u.withDO(u.DO.Session(config))
}

func (u userCourseGoodDo) Clauses(conds ...clause.Expression) *userCourseGoodDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userCourseGoodDo) Returning(value interface{}, columns ...string) *userCourseGoodDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userCourseGoodDo) Not(conds ...gen.Condition) *userCourseGoodDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userCourseGoodDo) Or(conds ...gen.Condition) *userCourseGoodDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userCourseGoodDo) Select(conds ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userCourseGoodDo) Where(conds ...gen.Condition) *userCourseGoodDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userCourseGoodDo) Order(conds ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userCourseGoodDo) Distinct(cols ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userCourseGoodDo) Omit(cols ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userCourseGoodDo) Join(table schema.Tabler, on ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userCourseGoodDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userCourseGoodDo) RightJoin(table schema.Tabler, on ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userCourseGoodDo) Group(cols ...field.Expr) *userCourseGoodDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userCourseGoodDo) Having(conds ...gen.Condition) *userCourseGoodDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userCourseGoodDo) Limit(limit int) *userCourseGoodDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userCourseGoodDo) Offset(offset int) *userCourseGoodDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userCourseGoodDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userCourseGoodDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userCourseGoodDo) Unscoped() *userCourseGoodDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userCourseGoodDo) Create(values ...*model.UserCourseGood) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userCourseGoodDo) CreateInBatches(values []*model.UserCourseGood, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userCourseGoodDo) Save(values ...*model.UserCourseGood) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userCourseGoodDo) First() (*model.UserCourseGood, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCourseGood), nil
	}
}

func (u userCourseGoodDo) Take() (*model.UserCourseGood, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCourseGood), nil
	}
}

func (u userCourseGoodDo) Last() (*model.UserCourseGood, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCourseGood), nil
	}
}

func (u userCourseGoodDo) Find() ([]*model.UserCourseGood, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserCourseGood), err
}

func (u userCourseGoodDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCourseGood, err error) {
	buf := make([]*model.UserCourseGood, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userCourseGoodDo) FindInBatches(result *[]*model.UserCourseGood, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userCourseGoodDo) Attrs(attrs ...field.AssignExpr) *userCourseGoodDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userCourseGoodDo) Assign(attrs ...field.AssignExpr) *userCourseGoodDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userCourseGoodDo) Joins(fields ...field.RelationField) *userCourseGoodDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userCourseGoodDo) Preload(fields ...field.RelationField) *userCourseGoodDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userCourseGoodDo) FirstOrInit() (*model.UserCourseGood, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCourseGood), nil
	}
}

func (u userCourseGoodDo) FirstOrCreate() (*model.UserCourseGood, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCourseGood), nil
	}
}

func (u userCourseGoodDo) FindByPage(offset int, limit int) (result []*model.UserCourseGood, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userCourseGoodDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userCourseGoodDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userCourseGoodDo) Delete(models ...*model.UserCourseGood) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userCourseGoodDo) withDO(do gen.Dao) *userCourseGoodDo {
	u.DO = *do.(*gen.DO)
	return u
}
