// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newWechatUser(db *gorm.DB, opts ...gen.DOOption) wechatUser {
	_wechatUser := wechatUser{}

	_wechatUser.wechatUserDo.UseDB(db, opts...)
	_wechatUser.wechatUserDo.UseModel(&model.WechatUser{})

	tableName := _wechatUser.wechatUserDo.TableName()
	_wechatUser.ALL = field.NewAsterisk(tableName)
	_wechatUser.ID = field.NewInt64(tableName, "id")
	_wechatUser.UserID = field.NewInt64(tableName, "user_id")
	_wechatUser.UnionID = field.NewString(tableName, "union_id")
	_wechatUser.NickName = field.NewString(tableName, "nick_name")
	_wechatUser.IconURL = field.NewString(tableName, "icon_url")
	_wechatUser.CreateAt = field.NewTime(tableName, "create_at")
	_wechatUser.UpdateAt = field.NewTime(tableName, "update_at")

	_wechatUser.fillFieldMap()

	return _wechatUser
}

// wechatUser 微信用户表
type wechatUser struct {
	wechatUserDo wechatUserDo

	ALL      field.Asterisk
	ID       field.Int64  // 主键ID,自增（无实际用途）
	UserID   field.Int64  // 全局用户id,user表主键
	UnionID  field.String // 微信唯一用户ID
	NickName field.String // 微信昵称
	IconURL  field.String // 128长度 微信头像
	CreateAt field.Time
	UpdateAt field.Time

	fieldMap map[string]field.Expr
}

func (w wechatUser) Table(newTableName string) *wechatUser {
	w.wechatUserDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wechatUser) As(alias string) *wechatUser {
	w.wechatUserDo.DO = *(w.wechatUserDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wechatUser) updateTableName(table string) *wechatUser {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.UserID = field.NewInt64(table, "user_id")
	w.UnionID = field.NewString(table, "union_id")
	w.NickName = field.NewString(table, "nick_name")
	w.IconURL = field.NewString(table, "icon_url")
	w.CreateAt = field.NewTime(table, "create_at")
	w.UpdateAt = field.NewTime(table, "update_at")

	w.fillFieldMap()

	return w
}

func (w *wechatUser) WithContext(ctx context.Context) *wechatUserDo {
	return w.wechatUserDo.WithContext(ctx)
}

func (w wechatUser) TableName() string { return w.wechatUserDo.TableName() }

func (w wechatUser) Alias() string { return w.wechatUserDo.Alias() }

func (w wechatUser) Columns(cols ...field.Expr) gen.Columns { return w.wechatUserDo.Columns(cols...) }

func (w *wechatUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wechatUser) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["id"] = w.ID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["union_id"] = w.UnionID
	w.fieldMap["nick_name"] = w.NickName
	w.fieldMap["icon_url"] = w.IconURL
	w.fieldMap["create_at"] = w.CreateAt
	w.fieldMap["update_at"] = w.UpdateAt
}

func (w wechatUser) clone(db *gorm.DB) wechatUser {
	w.wechatUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wechatUser) replaceDB(db *gorm.DB) wechatUser {
	w.wechatUserDo.ReplaceDB(db)
	return w
}

type wechatUserDo struct{ gen.DO }

func (w wechatUserDo) Debug() *wechatUserDo {
	return w.withDO(w.DO.Debug())
}

func (w wechatUserDo) WithContext(ctx context.Context) *wechatUserDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wechatUserDo) ReadDB() *wechatUserDo {
	return w.Clauses(dbresolver.Read)
}

func (w wechatUserDo) WriteDB() *wechatUserDo {
	return w.Clauses(dbresolver.Write)
}

func (w wechatUserDo) Session(config *gorm.Session) *wechatUserDo {
	return w.withDO(w.DO.Session(config))
}

func (w wechatUserDo) Clauses(conds ...clause.Expression) *wechatUserDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wechatUserDo) Returning(value interface{}, columns ...string) *wechatUserDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wechatUserDo) Not(conds ...gen.Condition) *wechatUserDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wechatUserDo) Or(conds ...gen.Condition) *wechatUserDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wechatUserDo) Select(conds ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wechatUserDo) Where(conds ...gen.Condition) *wechatUserDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wechatUserDo) Order(conds ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wechatUserDo) Distinct(cols ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wechatUserDo) Omit(cols ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wechatUserDo) Join(table schema.Tabler, on ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wechatUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wechatUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wechatUserDo) Group(cols ...field.Expr) *wechatUserDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wechatUserDo) Having(conds ...gen.Condition) *wechatUserDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wechatUserDo) Limit(limit int) *wechatUserDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wechatUserDo) Offset(offset int) *wechatUserDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wechatUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *wechatUserDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wechatUserDo) Unscoped() *wechatUserDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wechatUserDo) Create(values ...*model.WechatUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wechatUserDo) CreateInBatches(values []*model.WechatUser, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wechatUserDo) Save(values ...*model.WechatUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wechatUserDo) First() (*model.WechatUser, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WechatUser), nil
	}
}

func (w wechatUserDo) Take() (*model.WechatUser, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WechatUser), nil
	}
}

func (w wechatUserDo) Last() (*model.WechatUser, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WechatUser), nil
	}
}

func (w wechatUserDo) Find() ([]*model.WechatUser, error) {
	result, err := w.DO.Find()
	return result.([]*model.WechatUser), err
}

func (w wechatUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WechatUser, err error) {
	buf := make([]*model.WechatUser, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wechatUserDo) FindInBatches(result *[]*model.WechatUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wechatUserDo) Attrs(attrs ...field.AssignExpr) *wechatUserDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wechatUserDo) Assign(attrs ...field.AssignExpr) *wechatUserDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wechatUserDo) Joins(fields ...field.RelationField) *wechatUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wechatUserDo) Preload(fields ...field.RelationField) *wechatUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wechatUserDo) FirstOrInit() (*model.WechatUser, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WechatUser), nil
	}
}

func (w wechatUserDo) FirstOrCreate() (*model.WechatUser, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WechatUser), nil
	}
}

func (w wechatUserDo) FindByPage(offset int, limit int) (result []*model.WechatUser, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wechatUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wechatUserDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wechatUserDo) Delete(models ...*model.WechatUser) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wechatUserDo) withDO(do gen.Dao) *wechatUserDo {
	w.DO = *do.(*gen.DO)
	return w
}
