enum RouteName {
  /** 版本管理 */
  Edition = '/edition',
  /** 册别管理 */
  Subject = '/subject',
  /** 登录页 */
  Login = '/login',
  /** 首页 */
  Home = '/',
  /** 试卷编辑 */
  PaperEdit = '/paper/edit',
  /** 录播编辑 */
  RecordingCourseEdit = '/recording-course/edit',
  /** 试题编辑 */
  QuesEdit = '/ques/edit',
  /** 试卷审核 */
  PaperAudit = '/paper-audit/audit',
  /** 试卷库试卷 */
  BankPaperPaper = '/bank-paper/paper',
  /** 试题导入 */
  QuesImport = '/ques/import',
  /** 题库模块中题库类别 */
  BankModuleCategory = '/bank-module/category',
  /** 图片审核 */
  ImageAudit = '/image-audit/audit',
  /** 课程编辑 */
  CourseEdit = '/course/edit',
  /** 课程数据 */
  CourseData = '/course/data',
  /** 录播数据 */
  RecordingCourseData = '/recording-course/data',
  /** 课程系列课程 */
  CourseSeriesCourses = '/course-series/courses',
  /** 知识点树 */
  KnowledgeTree = '/knowledge/tree',
  /** 课件编辑 */
  PrepareCoursewareEdit = '/prepare-courseware/edit',
  /** 课件列表 */
  PrepareCourseware = '/prepare-courseware',
  KnowledgeContentEdit = '/knowledge-content/edit',
  /** 备课编辑 */
  PrepareLessonEdit = '/prepare-lesson/edit',
  /** 知识库审核 */
  KnowledgeContentAudit = '/knowledge-content-audit/audit',
  /** 知识库 */
  KnowledgeContent = '/knowledge-content',
  /** 公开知识库内容 */
  KnowledgeContentPublic = '/knowledge-content/public-content',
  /** 班级数据 */
  ClassData = '/class-list/class-data',
  /** 创建赠品订单 */
  AddGift = '/order-list/add-gift',
  /** 创建系统班（负责到高考）商品订单 */
  OrderListSubjectAdd = '/order-list/add-subject-goods',
  /** 创建辅导班商品订单 */
  OrderListCourseAdd = '/order-list/add-course-goods',
  /** 学员学习数据 */
  StudentLearningData = '/students-manage/learning-data',
  /** 新增/编辑课程商品（书课包和辅导班）订单 */
  EditCourseGoods = '/virtual-goods/edit-course-goods',
  /** 分销商商品管理 */
  ChannelGoodsManage = '/channel/goods-manage',
  /** 分销商订单结算 */
  ChannelOrderSettle = '/channel/order-settle',
  /** 分销商订单结算管理 */
  ChannelOrderSettleManage = '/channel/order-settle/order-manage',
  /** 分销商订单列表 */
  ChannelOrderList = '/channel/order-list',
  /** 分销商二维码管理 */
  ChannelQRCodeManage = '/channel/qr-code-manage'
}

export default RouteName
