// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminUserRole = "admin_user_role"

// AdminUserRole 管理员角色表
type AdminUserRole struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminUserID int64     `gorm:"column:admin_user_id;not null;comment:管理员ID" json:"admin_user_id"` // 管理员ID
	RoleID      int64     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`              // 角色ID
	UpdateAt    time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy    int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName AdminUserRole's table name
func (*AdminUserRole) TableName() string {
	return TableNameAdminUserRole
}
