// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMobileUser = "mobile_user"

// MobileUser 手机用户表
type MobileUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增，更换手机号码硬删除" json:"id"`          // 自增，更换手机号码硬删除
	UserID       int64     `gorm:"column:user_id;not null;comment:user表主键" json:"user_id"`                          // user表主键
	MobileAes    string    `gorm:"column:mobile_aes;not null;comment:aes加密后的手机号, 用于解密回显" json:"mobile_aes"`         // aes加密后的手机号, 用于解密回显
	MobileSha256 string    `gorm:"column:mobile_sha256;not null;comment:sha256加密后的手机号,用于全值搜索" json:"mobile_sha256"` // sha256加密后的手机号,用于全值搜索
	CreateAt     time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName MobileUser's table name
func (*MobileUser) TableName() string {
	return TableNameMobileUser
}
