// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permission"

// Permission 权限清单表
type Permission struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code     string    `gorm:"column:code;not null;comment:权限编码" json:"code"`                        // 权限编码
	Type     int32     `gorm:"column:type;not null;comment:1:菜单  2：操作" json:"type"`                  // 1:菜单  2：操作
	Name     string    `gorm:"column:name;not null;comment:权限名称" json:"name"`                        // 权限名称
	PagePath string    `gorm:"column:page_path;not null;comment:菜单路径" json:"page_path"`              // 菜单路径
	ParentID int64     `gorm:"column:parent_id;not null;default:-1;comment:父级权限ID" json:"parent_id"` // 父级权限ID
	Status   int32     `gorm:"column:status;not null;comment:1：正常 -1：禁用" json:"status"`              // 1：正常 -1：禁用
	Sort     int32     `gorm:"column:sort;not null;default:1" json:"sort"`
	Desc     string    `gorm:"column:desc;not null;comment:权限描述" json:"desc"` // 权限描述
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
