// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permission"

// RolePermission 角色权限表
type RolePermission struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID       int64     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`             // 角色ID
	PermissionID int64     `gorm:"column:permission_id;not null;comment:权限ID" json:"permission_id"` // 权限ID
	CreateAt     time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy     int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy     int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
